### ISSUE TITLE
Game Piece Alignment

### ISSUE THREAD

**Issue by KSatsujin** [FRC7540/WolfBot2023#6]
## Summary 

Robot needs to be able to align itself in order to place game pieces on targets.

## Context

- DEPENDENT ON CAMERA (LIMELIGHT) ON FRONT OF ROBOT
- Robot must use the cameras to align itself with the targets in order to place game pieces successfully on goals
- April tags and reflective tape used to align with targets
- Button bound to auto-alignment
- MUST be able to be cancelled
- Limelight needs to transfer vision data to network table and robot code needs to read it to determine how far it needs to move.

## Criteria for Acceptance

- Limelight must be able to recognize and align with April tags
- Limelight must be able to recognize and align with retro reflective tape
- Controller button activated
- Must be able to be cancelled

**Comment by EwanKannolt** [comment]
The PID control values that seem optimal for right now are:
P: 0.05
I: 0
D: 0
Today (Saturday Feb 18 of 2023) we tested the code on the robot and learned some things.
For one, field oriented drive doesn't work with auto align, whenever we press the auto align button in field oriented drive mode, it just drives backwards instead of strafing right or left to compensate for the nonalignment of the robot. The second thing that we found was that the pipeline for the retroreflective tape isn't sensitive enough to properly detect the tape every time.
